### PR TITLE
Initial commit of dictionaries chapter

### PR DESCRIPTION
**Pull request by Nanne**
Draft of a chapter about Python dictionaries. It starts off by explaining a scenario in which we'd like to store key:value pairs, and then explains how to do this using tuples, lists, and lists of tuples. It then continues on how to do this more easily with dicts, and finishes with some more advanced uses cases of dicts. Feedback is welcome.

### CODE REVIEW

**Comment by swubb** [comment]
Looks good! Very clear build up and clear examples. I would like maybe to add  some small exercises for the students throughout the notebook. I can add that later. Also some typos, but I dont know of any smart way of editing those quickly now xd

**Comment by Nanne** [comment]
I guess we could merge it and then you can make the changes that you'd like to see.

**Comment by swubb** [comment]
Shall I push the button or do you want to have the honor?

**Comment by swubb** [comment]
Or should it be Akos? :facepunch:

**Pull request merged**
